name: CI/CD Docker

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t hacked01/simple-app .

      - name: List local Docker images
        run: docker images

      - name: Trivyscan
        uses: aquasecurity/trivy-action@0.17.0
        with:
          image-ref: 'hacked01/simple-app'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH' 

      - name: Push Docker image
        run: docker push hacked01/simple-app

      - name: Run the image
        run: docker run --name pythonscript -p 3000:3000 hacked01/simple-app

      - name: List running Docker containers
        run: docker ps -a

      
