name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login to JFrog
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ secrets.JFROG_REGISTRY_URL }}  # e.g., mycompany.jfrog.io
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.JFROG_REGISTRY_URL }}/my-repo/my-image:latest .

      - name: Push to JFrog Artifactory
        run: |
          docker push ${{ secrets.JFROG_REGISTRY_URL }}/my-repo/my-image:latest
