name: CI 

on:
  push:
    branches:
      - main

jobs:
  build :
    runs-on: ubuntu

steps:
 - name: checkout
   uses: action/checkout@4.2.2

 - name: Docker login
   uses: docker/login-action@v3.4.0
   with:
     username: ${{secrets.DOCKER_USERNAME}}
     password: ${{secrets.DOCKER_PASSWORD}}
